version: '3.4'

services:
  api:
    image: ecomm
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3030:3030
    depends_on:
      - mongodb
    networks:
      - np-network

  mongodb:
    container_name: mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    image: mongo:latest
    ports:
      - 9090:9090
    user: root
    volumes:
      - mongodb:/var/lib/mongodb/
    networks:
      - np-network
volumes:
  mongodb:
networks:
  np-network:
