version: '3.4'

services:
  api:
    image: ecomm
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3030:3030
    depends_on:
      - mongodb
    networks:
      - np-network
    volumes:
      - ./src:/src

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    user: root
    volumes:
      - mongodb:/var/lib/mongodb/
    networks:
      - np-network
volumes:
  mongodb:
networks:
  np-network:
