on: [push, pull_request, workflow_dispatch]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: cd src && dotnet restore && cd ..
      - name: Build
        run: cd src && dotnet build --configuration Release --no-restore && cd ..
      - name: Test
        run: cd test && dotnet test --no-restore --verbosity normal && cd ..
